server:
  port: 0
  
spring:
  cloud:
    consul:
      discovery:
        instanceId: ${spring.application.name}:${random.value}
        health-check-interval: 15s
      config:
        management: 
          enabled: true

          